### PR TITLE
Fix re-sending activation email

### LINKED ISSUE #304: "Re-send activation link" link returns error 500
### Steps

1. In logged out state, go to https://www.scionlab.org/
2. Click on "Create Account"
3. Click on "Registered and didn't receive the activation link?"

### Observation

The link points to https://www.scionlab.org/registration/resend and results in a server error 500. The webserver exhibits the following stack trace:

```
Internal Server Error: /registration/resend
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django_registration/views.py", line 52, in dispatch
    return super().dispatch(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 133, in get
    return self.render_to_response(self.get_context_data())
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 66, in get_context_data
    kwargs['form'] = self.get_form()
  File "/usr/local/lib/python3.6/site-packages/django_registration/views.py", line 71, in get_form
    form_model = form_class._meta.model
AttributeError: type object 'RegistrationResendForm' has no attribute '_meta'
```

### PR DESCRIPTION
**Pull request by matzf**
* Fix form in UserRegistrationResendView
  Quirky, see comment on RegistrationResendForm.
  Was probably broken since updating the django-registration dependency from 3.0 to 3.1.
* Add tests for resending activation email and split up registration test into smaller units.

Fixes #304

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/305)

### CODE REVIEW

**Review by cmeury — COMMENTED** [review]
That is indeed very quirky. Great to see the tests covering this use case. LGTM!

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/305#-:-MGrLMqSACpQOHWAQ3q_:b42kx4m)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @cmeury)

**Review by cmeury — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/305#-:-MGrLcQZB-ll29zQcaeF:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @cmeury)

**Review by cmeury — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scionlab/305)* status: :shipit: complete! all files reviewed, all discussions resolved
